[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "654e0c96a2627c0afdc34e9507a560e8380ea8c6"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "f6887c55d44fab81b9e9482510f20bb60a4cc10dae1fe2340befc2bcd471bc05"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.aarch64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "37acf59e08c4013b7b665e2cd8b6f565e619565f"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "44fff8172a08bea0e4e389ca978825830b6d13c90b3d4095eeb63db7074acb3a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.aarch64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "df8692e7721ea92b10f4b83e83721663215b3e15"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "40789350359a66e92fb0b49b1335fec3e7d56b9730216e533deba87f206f2b3c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.aarch64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "47e7b16e2113ce63b2acb8497f86ea7c89dbab6a"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "176ba8ce0efb51f12a5ca81bf33a35a4b354dba72a4f4789771ebaaf72cfbb9e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "997f28c328e6930458bebd9ea94e1c68e726184a"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "c71e62965b584a87f521cc364574144135716661df22c128d69bfd9a4ec88afa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a3edbe42568d787e5945bf4001b378803804358"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "f85d56aff6f13dd8efbef9455990654dcd4171e5b86ba58469abaacd1f68a145"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9d535fa88310c44f309f18012129519523c2555"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "141d03c3201440c46a8768d5bc55d082c58dea720d28c2b9b326eb3e5149dfe4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8cf11bef7036eeed7fa9bce5c6715e282e85ebd7"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "f353574c739ee0a283d7c04c25bb7587b0d358c2bfe985652e379471410666a0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "f936bc577c2755becdf91061fd36a3cbec64b806"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "cbb12d7ebe8ec575dbc394d15d6a57a288a444a7f7ed4fc5e15853255a1987aa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.i686-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "eae7b9b05bb299c71cd39ddeb1e003db083867c4"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "0f926ef8872f46b566cb71ebbee3a59f89ba46b1b0f965bd6605463e05a3c1ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.i686-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "powerpc64le"
git-tree-sha1 = "81ab8e258ef9e61314e4e1f06352b8b1fd364287"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "e86ff838d710febdc4b8ab59bcbc94ae4eba2ac773e21838d748880f6073aca5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "riscv64"
git-tree-sha1 = "91a0b008788d84e33c566387735be6fbaf63467f"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "1bdaad54e823eb886eb21cd639bf14492f6c1bc2946ce4f04e40dfaa0e9ae950"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.riscv64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "7b96098aced574ffad65954778e7cec1e3f0a166"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "8d2c9f383402d21ba32a8970e5ca0bf23f5c1eaacde49235f2bd71de5e84a950"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.x86_64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "a4c048a3f4f737110aecf4eb9299ab1ec3b1a3af"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "2d2c159ac7c612fb5c755b5c08049ed1cb4c5a628988199c0bb6a7dc339e67e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.x86_64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "8956e2507a93363fbc0d1e0fa8fe7d8ae10067c3"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "8e24c73f2ca1dedc8c5ed81a537e9019bef8c13a5a2e376e13ddc63a182fc08d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.x86_64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "edfd337e2fc0e9a61b0c9a8ce48b49a9786ceada"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "510d174779f8985273ad730762e17b1ea61bc2a4e9fcf9043918bb34c2634abe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "11b6eb89eef5632df289d9708dee0da8aeadf138"
os = "windows"

    [[aws_c_compression.download]]
    sha256 = "f85c3c43db607411cea806220fa95c4eca4bc845b92d91b5ddda76f376a59e4c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.3.3+0/aws_c_compression.v0.3.3.x86_64-w64-mingw32.tar.gz"
