[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "27ea81ee057562a85ac24f588afaa487b97e47bf"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "7d0bd1c064c21033a0fdb54ec4c40bffe20c7223f62487fdcfcb8742776031b3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.aarch64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "c88082783c6ab2e6852830928d452267544b968e"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "1380af555aa980f9fea70013b1d72eb6026847c49ae4812e23db0d62d768056d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.aarch64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "564d401c431cf968224fba3f9cd89a4337122b83"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "00240e6cf0876a88458a4ef508dfe29bda1b000d1ffcb67d076fc7ad8b01b23b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.aarch64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "c3768d4bf8fc73893fabccc791a2297d82c6445e"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "64855d964a6efe6cc24071761e72d9c13ee4a89f3d62d48bd598f6511046fbde"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9faf8d0f8955cd2c0c92f33c93220747b21deecc"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "d1a512629fd9c2fd5b50d65aa1b7b727f9940fb1d3efec065c126421130baa17"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f1fca9fe746e1b7685772fa8f31260d031d5874"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "bf1671c3dec360134684bba140afec9a6bbb2fcadc9b1f8a54582980abf84c00"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "143618dc0c40486263d53d5948a9e3801a3cfd4b"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "849a3a8d154f4aa5abc47fd94360810809132707439a289f43914b6683a256fe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48cbb1394f660b3c11f1f1aaf12e41ee7b57f3b5"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "87f388e347c476a9330cf2a94abb544f2ff88f364a3a376d6a1e3e716613a5f6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "c2d7ed6376bc617b23167a265fc08bb6d14f9112"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "d7c99d72e11dba5abf8a38a6aa8ed4eedd6ec30d288dc5fc0d25536355f157fe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.i686-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "58a56ec0933d0632fcd96cb48cca8e045d8c7313"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "8dd5a1e897840efc475fa6fc7ac2c179939e2d2754bd12b17910a61599738c2e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.i686-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "powerpc64le"
git-tree-sha1 = "f63ca1ee5a56cc66cad9df8fd7ce30a1396f222e"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "5348346f0b6013a7d52657da2999098a609e2e445d18095c9f675f72b741cebc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "riscv64"
git-tree-sha1 = "878c73feebc770a9496ba5ccf5523847f862b401"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "d1826edbfec13b4fd4f758a1ad49fa7f158dbbddecf3e92503d9b8222b82fe26"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.riscv64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "f1d266abafe12cf14b1b3180dd631f2a7e56a756"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "6658d5315306a678eb743aa6b8d85ce1f89923619250bf03c2280f47574817b1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.x86_64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "49bb4e64e1fd94d50e9c9c3fe95d41878be6e7aa"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "f7d3a51ef52cb50b7718893a43f2478bae3258399409d65e640edf6de95394a8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.x86_64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "5a713d381008f28a3fcb7c7aeaf07e7ec1b7719d"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "793fb0241ed5d56aa5d32647b6111352b454aa0dcf99e896f652c328bae3c863"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.x86_64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "47b4568ecd30f3575e6042cdd163bf785b8cb1dd"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "4078cd0f906976683dfe6dd43ac29c69d2a46f89632463028e55f387c65347d7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "784b48c2066973fb9d67871e85c7f7c37e5d8ff0"
os = "windows"

    [[aws_c_compression.download]]
    sha256 = "9947d8f1a46d1e99b5633f6537f4ead55667c1a7fe80f56cee2825d2d1d30ff3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v1.0.0+0/aws_c_compression.v1.0.0.x86_64-w64-mingw32.tar.gz"
