[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "ac6ad5c6cc6429dc36d0bb12f85f7a7f98cd50ff"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "2374c9f0ea0e651be48babcdefe1aed9db3a674b546bbb8a5820e24b2ffb6637"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.aarch64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "d313c99f3073853185236c605090446e769140e7"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "b875bcc106ffd262ec21fddf8040af1bd60465c3573cc069dd16a3a76afc4ce6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.aarch64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "979e34865b6408a3e9e550366f4cabc288790131"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "21c776cd7da3f78ee15d9df84420ee4bfdd4b2e3d92dad690219ad2f9ea6610e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.aarch64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a70418883aac4247d7728209e2cb9baf25accef"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "983618e4b9ad46aa8ea14da07c0e6cbdc7ead5c1c9bacac10cc7ea3907b3639c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36e269ab7c82d70acffe5f2f0081b3120d130151"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "8a1597b442a169f21abe16badb7824a9c8ff2e5b569938688ea7af47485faba1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.armv6l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3027f12c19c091d52e1e2175baaef0e7a482a911"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "22b78943f47acf677436e3a71ee3e96ecce1104c27d6287a9ca07602ca1be9d7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a21133a839472a5fdb9323bd96ad05e2fdd47fc"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "b3137c33ded0cfe652f77c14adfcb884b9a8e6b09c9da9d82c426cd6398ed0d6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.armv7l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "bc20ad8a64de11a859ee4ebf0dd593ab6c12d4fa"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "a1a956c252b3d4855ebe04f0e133676e48d6ebb027b36a65ee60b522ad63da8e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.i686-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "a02c7bd2d6a8d6720d7282fc64cb089f4faefe33"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "2f36ef851278213ae0ee9d511fb39bbb1029d6550667de131d1ab2d9c92f2954"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.i686-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "powerpc64le"
git-tree-sha1 = "195595efa6bf84676489a4ff44c8d0d81925b92c"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "880d302373e203149cd3ee4becc0d0fa276824a76fa11bfc601f199485730a06"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.powerpc64le-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "e5d81aae2d428749bbc3b5671497834c138fa3af"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "5485a8f3e77128f22bc315c5a3ea8a98a03aeb85d06ed28b293be2003f278231"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.x86_64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "11d38ddcc59521a76912c15c81921e4dc086841e"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "9df337eeebbfd0ac97d26dadb93252824178e78a359bc08b3b204b2e4a45d709"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.x86_64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "ed20f8c7264a55f9b3819fa0ad8e1e087e6760a3"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "749cf22b594e72a7ad014c632f8f24f92773ca359187c08b6b06be618db4a966"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.x86_64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "67d69f01f4a0ba6315aa05b12d81ff32301e7729"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "afb757e972f0c4a289baf9bac85fb5f97cb5b82392351c3a71f2a3ad7537cc59"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.x86_64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "6884b4b36dd8f6cb78c3868e5d54b4ef5500d115"
os = "windows"

    [[aws_c_compression.download]]
    sha256 = "932f41adecd59b3878f9da057dab3a3c453b3524ea6a8175d45b0250f58ef0a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.18+0/aws_c_compression.v0.2.18.x86_64-w64-mingw32.tar.gz"
