[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "0a091265ee37635f00131ea7b255c4ec036fe568"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "4ada094df3bdb6a6614efffc643cd3f8629f39184f47056a76d87a5a4198e714"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.aarch64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "d313c99f3073853185236c605090446e769140e7"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "b875bcc106ffd262ec21fddf8040af1bd60465c3573cc069dd16a3a76afc4ce6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.aarch64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "aarch64"
git-tree-sha1 = "979e34865b6408a3e9e550366f4cabc288790131"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "21c776cd7da3f78ee15d9df84420ee4bfdd4b2e3d92dad690219ad2f9ea6610e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.aarch64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a70418883aac4247d7728209e2cb9baf25accef"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "983618e4b9ad46aa8ea14da07c0e6cbdc7ead5c1c9bacac10cc7ea3907b3639c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36e269ab7c82d70acffe5f2f0081b3120d130151"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "8a1597b442a169f21abe16badb7824a9c8ff2e5b569938688ea7af47485faba1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.armv6l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3027f12c19c091d52e1e2175baaef0e7a482a911"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "22b78943f47acf677436e3a71ee3e96ecce1104c27d6287a9ca07602ca1be9d7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_compression]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a21133a839472a5fdb9323bd96ad05e2fdd47fc"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "b3137c33ded0cfe652f77c14adfcb884b9a8e6b09c9da9d82c426cd6398ed0d6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.armv7l-linux-musleabihf.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "bc20ad8a64de11a859ee4ebf0dd593ab6c12d4fa"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "a1a956c252b3d4855ebe04f0e133676e48d6ebb027b36a65ee60b522ad63da8e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.i686-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "i686"
git-tree-sha1 = "a02c7bd2d6a8d6720d7282fc64cb089f4faefe33"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "2f36ef851278213ae0ee9d511fb39bbb1029d6550667de131d1ab2d9c92f2954"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.i686-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "powerpc64le"
git-tree-sha1 = "195595efa6bf84676489a4ff44c8d0d81925b92c"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "880d302373e203149cd3ee4becc0d0fa276824a76fa11bfc601f199485730a06"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.powerpc64le-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "c2949cc89f9b914b48c502c88a2d346e8f2eb489"
os = "macos"

    [[aws_c_compression.download]]
    sha256 = "ddf1d0725da31952194e52fd220b12246a3ad72592e45e522408ffd14c1089de"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.x86_64-apple-darwin.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "11d38ddcc59521a76912c15c81921e4dc086841e"
libc = "glibc"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "9df337eeebbfd0ac97d26dadb93252824178e78a359bc08b3b204b2e4a45d709"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.x86_64-linux-gnu.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "ed20f8c7264a55f9b3819fa0ad8e1e087e6760a3"
libc = "musl"
os = "linux"

    [[aws_c_compression.download]]
    sha256 = "749cf22b594e72a7ad014c632f8f24f92773ca359187c08b6b06be618db4a966"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.x86_64-linux-musl.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "6cd43c9596dbdde79d74eb5cf76dc36a5ee0161e"
os = "freebsd"

    [[aws_c_compression.download]]
    sha256 = "66d4cbb7f2c42c11e6820dc73c2d576e217f1c906f156232cbab1142f8b6ff38"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.x86_64-unknown-freebsd.tar.gz"
[[aws_c_compression]]
arch = "x86_64"
git-tree-sha1 = "6884b4b36dd8f6cb78c3868e5d54b4ef5500d115"
os = "windows"

    [[aws_c_compression.download]]
    sha256 = "932f41adecd59b3878f9da057dab3a3c453b3524ea6a8175d45b0250f58ef0a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_compression_jll.jl/releases/download/aws_c_compression-v0.2.19+0/aws_c_compression.v0.2.19.x86_64-w64-mingw32.tar.gz"
