# Autogenerated wrapper script for aws_c_compression_jll for aarch64-linux-gnu
export libaws_c_compression

JLLWrappers.@generate_wrapper_header("aws_c_compression")
JLLWrappers.@declare_file_product(libaws_c_compression)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libaws_c_compression,
        "lib/libaws-c-compression.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
