# Autogenerated wrapper script for aws_c_compression_jll for armv7l-linux-gnueabihf
export libaws_c_compression

using aws_c_common_jll
JLLWrappers.@generate_wrapper_header("aws_c_compression")
JLLWrappers.@declare_library_product(libaws_c_compression, "libaws-c-compression.so.1.0.0")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_common_jll)
    JLLWrappers.@init_library_product(
        libaws_c_compression,
        "lib/libaws-c-compression.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
