# Autogenerated wrapper script for aws_c_compression_jll for x86_64-apple-darwin
export libaws_c_compression

using aws_c_common_jll
JLLWrappers.@generate_wrapper_header("aws_c_compression")
JLLWrappers.@declare_library_product(libaws_c_compression, "@rpath/libaws-c-compression.1.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_common_jll)
    JLLWrappers.@init_library_product(
        libaws_c_compression,
        "lib/libaws-c-compression.1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
